In [2]:
# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
dansbecker_melbourne_housing_snapshot_path = kagglehub.dataset_download('dansbecker/melbourne-housing-snapshot')

print('Data source import complete.')

Downloading from https://www.kaggle.com/api/v1/datasets/download/dansbecker/melbourne-housing-snapshot?dataset_version_number=5...

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 451k/451k [00:00<00:00, 22.0MB/s]

Extracting files...
Data source import complete.

In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
## Avvalgi amaliyotda `GitHub`ga yuklangan `melb_data.csv` faylni `df` ga chaqirib oling

#Javobingizni shu yerga yozing
df=pd.read_csv('https://raw.githubusercontent.com/MuhammadaliSadulloh/Data_science/refs/heads/main/melb_data.csv?raw=true')

In [12]:
df=pd.read_csv('https://raw.githubusercontent.com/MuhammadaliSadulloh/Data_science/refs/heads/main/melb_data.csv?raw=true')

In [5]:
df['BuildingArea'].mean()

151.96764988779805

In [ ]:
# Mening javobim
df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/blob/main/melb_data.csv?raw=true")
df.head()

Yuqoridagi Dataframe Melburn shahri uchun sotuvdagi uylar haqida m'lumotlarni jamlagan.

Quyida jadvalning ba'zi sutunlari tarjimasi berilgan (qolganini o'zingiz Google yordamida tarjima qilishingiz mumkin):
- `Room` - xonalar soni
- `Type` - uyning turi (h - villa/kottej/hovli; u - kvartira; t - shahardagi hovli)
- `Price` - narx
- `Bathroom` - tualet-vanna
- `Landsize` - yerning maydoni (hovli uchun)
- `BuildingArea` - Bino qurilgan yerning maydoni
- `YearBuilt` - qurilgan yili
- `Lattitude` va `Longitude` - GPS kordinatalar
- `Regionname` - Region

# ðŸ”º DIQQAT!
#### **Agar alohida aytilmagan bo'lsa, `df`ga kiritilgan o'zgartirishlarni saqlamang (`inplace=False`)**

## 1-VAZIFA. `df` dagi barcha ustunlardagi`NaN` qiymatlar sonini chiqaring

In [6]:
#Javobingizni shu yerga yozing
df.isnull().sum().sum()

13256

## 2-VAZIFA. `df` barcha `NaN` qiymatlarni 0 bilan almashtiring

In [9]:
#Javobingizni shu yerga yozing
df.fillna(0,inplace=True)

## 3-VAZIFA. Quyidagi 2 ustun uchun o'rta qiymatlarni hisoblang:
- BuildingArea
- YearBuilt (**butun son qaytishi kerak**)

In [10]:
#Javobingizni shu yerga yozing
df['BuildingArea'].mean()

79.78861146539029

In [ ]:
int(df['YearBuilt'].mean())

1964

**To'g'ri javob:**

In [ ]:
print(df['BuildingArea'].mean())
print(int(df['YearBuilt'].mean()))

## 4-VAZIFA: `BuildingArea` va `YearBuilt` ustunlaridagi `NaN` qiymatlarni shu sutun uchun o'rta qiymatlar bilan almashtiring
**DIQQAT!** `YearBuilt` ustuni qiymatlari butun son bo'lishi kerak

In [ ]:
#Javobingizni shu yerga yozing
df.fillna({'YearBuilt':df['YearBuilt'].mean(),'BuildingArea':df['BuildingArea'].mean()})

,Unnamed: 0,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,...,1.0,1.0,202.0,151.96765,1964.684217,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,...,1.0,0.0,156.0,79.00000,1900.000000,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,...,2.0,0.0,134.0,150.00000,1900.000000,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,...,2.0,1.0,94.0,151.96765,1964.684217,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,...,1.0,2.0,120.0,142.00000,2014.000000,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13575,13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,...,2.0,2.0,652.0,151.96765,1981.000000,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,...,2.0,2.0,333.0,133.00000,1995.000000,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13577,13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,...,2.0,4.0,436.0,151.96765,1997.000000,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
13578,13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,...,1.0,5.0,866.0,157.00000,1920.000000,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
13579,13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,...,1.0,1.0,362.0,112.00000,1920.000000,NaN,-37.81188,144.88449,Western Metropolitan,6543.0

**To'g'ri javob:**

In [ ]:
df.fillna({'BuildingArea':df['BuildingArea'].mean(), 'YearBuilt':int(df['YearBuilt'].mean())})

In [13]:
df[df['Rooms'] == 5]['BuildingArea'].mean()

405.6073468390805

In [14]:
df[(df['Rooms'] == 4) & (df['Type'] == 't')]['BuildingArea'].mean()

194.6341836734694

## 5-VAZIFA. `.groupby()`
Ustun uchun o'rta qiymat har doim ham aniq bo'lavermaydi. Keling avval `YearBuilt` ustuni uchun aniqroq qiymat topishga harakat qilamiz.

Buning uchun `Regionname` ustuni qiymatlaridan foydalanishimiz mumkin, ya'ni bir Regiondagi binolar tahminan bir hil yillarda qurilgan deb tahmin qilsak bo'ladi.

### 5.1 `.groupby()` yordamida `df` qiymatlarini `Regionname` ustuni bo'yicha guruhlang va `YaerBuilt` ustuni uchun o'rta qiymatni hisoblang.

In [ ]:
#Javobingizni shu yerga yozing
df.groupby(['Regionname']).YearBuilt.mean().astype(int)

Regionname
Eastern Metropolitan          1971
Eastern Victoria              1984
Northern Metropolitan         1962
Northern Victoria             1986
South-Eastern Metropolitan    1976
Southern Metropolitan         1960
Western Metropolitan          1968
Western Victoria              1982
Name: YearBuilt, dtype: int64

**To'g'ri javob:**

In [ ]:
df.groupby(['Regionname']).YearBuilt.mean().astype(int)

### 5.2. `df` `YearBuilt` ustunidagi `NaN` qiymatlarni yuqoridagi qiymatlar bilan almashtiring.
`df[df.Regionname='Eastern Metropolitan']=...`

Har bir `Regionname` uchun qiymatlarni bittalab kiritmaslik uchun for siklidan foydalanishingiz mumkin.

In [ ]:
#Javobingizni shu yerga yozing
a=df.groupby(['Regionname']).YearBuilt.mean()
for i in a.index:
  df[df.Regionname==i]=df[df.Regionname==i].fillna({'YearBuilt':a[i]})

In [ ]:
df.sample(5)

,Unnamed: 0,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
3598,3598,Kew,73 Cobden St,2,h,1326000.0,S,Nelson,7/11/2016,5.6,...,1.0,2.0,405.0,80.0,1890.000000,Boroondara,-37.8012,145.0361,Southern Metropolitan,10331.0
7663,7663,Burwood,1/10 Gillard St,2,h,870000.0,S,Noel,13/05/2017,11.7,...,1.0,1.0,271.0,160.0,1960.523777,Whitehorse,-37.8512,145.1145,Southern Metropolitan,5678.0
3382,3382,Ivanhoe,6/11 Rose St,2,u,465000.0,S,Barry,14/05/2016,7.9,...,1.0,1.0,795.0,NaN,1970.000000,Banyule,-37.7744,145.0415,Eastern Metropolitan,5549.0
2116,2116,Collingwood,8/115 Oxford St,2,u,800000.0,VB,Nelson,25/02/2017,1.6,...,1.0,1.0,0.0,91.0,1900.000000,Yarra,-37.8026,144.9848,Northern Metropolitan,4553.0
8366,8366,South Yarra,806/800 Chapel St,2,u,800000.0,VB,Beller,6/05/2017,3.3,...,2.0,2.0,0.0,NaN,2000.000000,Stonnington,-37.8361,144.9966,Southern Metropolitan,14887.0

**To'g'ri javob**

In [ ]:
groups = df.groupby(['Regionname']).YearBuilt.mean() # Bu Series obyekti
for idx in groups.index:
  df[df.Regionname==idx] = df[df.Regionname==idx].fillna({'YearBuilt':groups[idx]})

### `YearBuilt` uchun yana ham aniqroq o'rta qiymat hisoblashning qanday yo'lini taklif qilgan bo'lar edingiz?

## 6-VAZIFA. `BuildingArea` ustunidagi `NaN` qiymatlarni to'ldiramiz
`BuildingArea` bino qurilgan yerning maydonini bildiradi. Bu qiymatlarni tahmin qilish uchun qaysi ustun qiymatlaridan foydalanish to'g'ri deb hisoblaysiz?

In [ ]:
df.groupby(['Regionname']).BuildingArea.mean()

Regionname
Eastern Metropolitan           178.001521
Eastern Victoria               183.645000
Northern Metropolitan          124.177723
Northern Victoria             1746.374286
South-Eastern Metropolitan     162.734296
Southern Metropolitan          153.580962
Western Metropolitan           144.697623
Western Victoria               134.683810
Name: BuildingArea, dtype: float64

In [ ]:
a = df.groupby(['Regionname'])['BuildingArea'].mean()
for i in a.index:
    df.loc[df['Regionname'] == i, 'BuildingArea'] = df.loc[df['Regionname'] == i, 'BuildingArea'].fillna(a[i])

In [ ]:
df.isnull().sum()

Unnamed: 0          0
Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Date                0
Distance            0
Postcode            0
Bedroom2            0
Bathroom            0
Car                62
Landsize            0
BuildingArea        0
YearBuilt           0
CouncilArea      1369
Lattitude           0
Longtitude          0
Regionname          0
Propertycount       0
dtype: int64

### 6.1 `df`ni xonalar soni bo'yicha o'rta qiymat olib ko'ring

In [ ]:
df.groupby('Rooms').BuildingArea.mean()

Rooms
1      97.176686
2     118.772426
3     143.932215
4     187.994069
5     300.807028
6     245.956933
7     262.746061
8     204.167646
10    124.177723
Name: BuildingArea, dtype: float64

### 6.2 Xonalar va uy turi bo'yicha o'rta qiymatni olib ko'ring.

In [ ]:
#Javobingizni shu yerga yozing
df.groupby(['Rooms','Type']).BuildingArea.mean()

Rooms  Type
1      h       123.345932
       t        90.155536
       u        94.822791
2      h       125.199777
       t       129.019874
       u       112.426299
3      h       145.142580
       t       142.741078
       u       132.708849
4      h       188.625587
       t       180.816932
       u       163.567462
5      h       301.995414
       t       160.339829
6      h       247.092645
       u       171.000000
7      h       262.746061
8      h       215.594778
       u       124.177723
10     h       124.177723
Name: BuildingArea, dtype: float64

### 6.3 Ahamiyat bering, 10 xonalik uylar uchun o'rta qiymat chiqmayapti. Bu nimadan dalolat beradi? Jami 10 xonalik uylar nechta? Ular bilan qanday yo'l tutishni maslahat berasiz?

In [ ]:
#Javobingizni shu yerga yozing
df[df['Rooms'] == 10]

,Unnamed: 0,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
11304,11304,Bundoora,5 Ball Ct,10,h,900000.0,PI,Ray,15/07/2017,12.1,...,3.0,2.0,313.0,124.177723,2006.0,Darebin,-37.71098,145.05381,Northern Metropolitan,10175.0

### 6.4 `BuildingArea` ustunidagi mavjud `NaN` qiymatlarni o'zingiz to'g'ri deb bilgan usul bilan to'ldiring.

In [ ]:
df.isnull().sum()

Unnamed: 0          0
Suburb              0
Address             0
Rooms               0
Type                0
Price               0
Method              0
SellerG             0
Date                0
Distance            0
Postcode            0
Bedroom2            0
Bathroom            0
Car                62
Landsize            0
BuildingArea        0
YearBuilt           0
CouncilArea      1369
Lattitude           0
Longtitude          0
Regionname          0
Propertycount       0
dtype: int64

### 7-VAZIFA. Yuqoridagi vazifalardan so'ng, bizda faqatgina `CouncilArea` ustunida `NaN` qiymatlar qolishi kerak xolos.
**Bu ustundagi `NaN` qiymatlarni avvalgi qatordagi qiymatlar bilan to'ldirib keting. Natijani saqlab qoling**

In [ ]:
df.CouncilArea.fillna(method='ffill',inplace=True)

<ipython-input-70-ff8e0565bb91>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.CouncilArea.fillna(method='ffill',inplace=True)
<ipython-input-70-ff8e0565bb91>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.CouncilArea.fillna(method='ffill',inplace=True)

## YAKUNIY JADVAL
Ahamiyat bering, yakuniy jadvalda `NaN` qiymatlar bo'lmasligi kerak.

In [ ]:
df.isnull().sum()

Unnamed: 0       0
Suburb           0
Address          0
Rooms            0
Type             0
Price            0
Method           0
SellerG          0
Date             0
Distance         0
Postcode         0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
YearBuilt        0
CouncilArea      0
Lattitude        0
Longtitude       0
Regionname       0
Propertycount    0
dtype: int64