In [288]:
!pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in c:\programdata\anaconda3\lib\site-packages (2.9.10)

In [289]:
from pprint import pprint as print
import psycopg2 as psql

In [290]:
pdb = psql.connect(
    host = "localhost",
    database = "postgres",
    user = "postgres",
    password = "74123"
)
cursor1 = pdb.cursor()
cursor1.execute("SELECT version()")
print(cursor1.fetchone())

('PostgreSQL 17.2 on x86_64-windows, compiled by msvc-19.42.34433, 64-bit',)

In [291]:
cursor1.execute('SELECT * FROM car ORDER BY id ASC;')
cursor1.fetchall()

[(1, 'Chevrolet', 'G-Series G30', Decimal('1995'), Decimal('56733.89')),
 (2, 'Toyota', '4Runner', Decimal('1996'), Decimal('30391.77')),
 (3, 'Lexus', 'RX', Decimal('2012'), Decimal('6537.82')),
 (4, 'Dodge', 'Ram 2500', Decimal('1996'), Decimal('48262.84')),
 (5, 'Mitsubishi', 'GTO', Decimal('1993'), Decimal('70156.81')),
 (6, 'Lexus', 'LS', Decimal('2007'), Decimal('23342.25')),
 (7, 'Porsche', 'Boxster', Decimal('2000'), Decimal('58733.11')),
 (8, 'Subaru', 'Legacy', Decimal('1990'), Decimal('54683.40')),
 (9, 'GMC', 'Savana 3500', Decimal('2002'), Decimal('90809.33')),
 (10, 'Mitsubishi', 'Galant', Decimal('1995'), Decimal('89616.37')),
 (11, 'GMC', 'Suburban 1500', Decimal('1996'), Decimal('18932.28')),
 (12, 'GMC', 'Envoy XL', Decimal('2004'), Decimal('67920.47')),
 (13, 'GMC', 'Rally Wagon 1500', Decimal('1992'), Decimal('39693.16')),
 (14, 'Toyota', 'Matrix', Decimal('2011'), Decimal('28009.56')),
 (15, 'Honda', 'Civic Si', Decimal('2003'), Decimal('75689.41')),
 (16, 'Lexus', 'SC', Decimal('2000'), Decimal('7624.16')),
 (17, 'Buick', 'LaCrosse', Decimal('2007'), Decimal('45544.37')),
 (18, 'Mazda', 'Mazda6', Decimal('2008'), Decimal('84934.48')),
 (19, 'Pontiac', 'Fiero', Decimal('1985'), Decimal('80988.89')),
 (20, 'Mercedes-Benz', '190E', Decimal('1992'), Decimal('56436.72')),
 (21, 'Buick', 'Rendezvous', Decimal('2006'), Decimal('10115.55')),
 (22, 'Ford', 'Crown Victoria', Decimal('2010'), Decimal('78396.83')),
 (23, 'Mitsubishi', 'Tredia', Decimal('1985'), Decimal('57687.25')),
 (24, 'Audi', 'A8', Decimal('2000'), Decimal('58122.96')),
 (25, 'Kia', 'Rio', Decimal('2003'), Decimal('76142.76')),
 (26, 'Audi', 'A3', Decimal('2012'), Decimal('43063.28')),
 (27, 'Lincoln', 'Continental', Decimal('2002'), Decimal('50284.78')),
 (28, 'Porsche', '944', Decimal('1991'), Decimal('81206.05')),
 (29, 'Chevrolet', 'Cavalier', Decimal('2003'), Decimal('9454.43')),
 (30, 'Subaru', 'Forester', Decimal('2011'), Decimal('63286.20')),
 (31, 'Ford', 'Bronco', Decimal('1993'), Decimal('73270.74')),
 (32, 'Dodge', 'Sprinter', Decimal('2009'), Decimal('48291.73')),
 (33, 'Toyota', 'Camry', Decimal('2000'), Decimal('15337.75')),
 (34, 'Oldsmobile', 'Alero', Decimal('2003'), Decimal('19640.87')),
 (35, 'Ford', 'Laser', Decimal('1989'), Decimal('97915.54')),
 (36, 'Toyota', 'Avalon', Decimal('2001'), Decimal('14365.91')),
 (37, 'Dodge', 'Durango', Decimal('2006'), Decimal('84132.43')),
 (38, 'Kia', 'Rio', Decimal('2004'), Decimal('99143.32')),
 (39, 'Hyundai', 'Tiburon', Decimal('2000'), Decimal('70356.41')),
 (40, 'Lamborghini', 'Gallardo', Decimal('2007'), Decimal('6895.79')),
 (41, 'BMW', '3 Series', Decimal('2012'), Decimal('96800.06')),
 (42, 'Dodge', 'Dakota', Decimal('1994'), Decimal('55491.85')),
 (43, 'Chrysler', 'New Yorker', Decimal('1992'), Decimal('45507.37')),
 (44, 'Mercedes-Benz', 'SL-Class', Decimal('2001'), Decimal('91070.07')),
 (45, 'Mitsubishi', 'Eclipse', Decimal('2008'), Decimal('66393.35')),
 (46, 'Mercedes-Benz', 'E-Class', Decimal('1997'), Decimal('60954.29')),
 (47, 'Maserati', 'Quattroporte', Decimal('1984'), Decimal('84148.79')),
 (48, 'Kia', 'Sedona', Decimal('2012'), Decimal('37631.29')),
 (49, 'Lexus', 'IS', Decimal('2009'), Decimal('38720.66')),
 (50, 'Chevrolet', 'Impala', Decimal('2005'), Decimal('53079.12')),
 (51, 'Mitsubishi', 'Endeavor', Decimal('2006'), Decimal('4640.06')),
 (52, 'Chevrolet', 'Silverado 2500', Decimal('2006'), Decimal('60825.44')),
 (53, 'Ford', 'Fusion', Decimal('2012'), Decimal('76446.29')),
 (54, 'Ford', 'Bronco II', Decimal('1990'), Decimal('66117.08')),
 (55, 'Lotus', 'Esprit', Decimal('1988'), Decimal('14587.66')),
 (56, 'Mazda', 'Millenia', Decimal('1997'), Decimal('29763.61')),
 (57, 'Chevrolet', 'Camaro', Decimal('1972'), Decimal('4053.14')),
 (58, 'Jaguar', 'X-Type', Decimal('2008'), Decimal('58196.86')),
 (59, 'Mercedes-Benz', 'R-Class', Decimal('2011'), Decimal('67379.42')),
 (60, 'Lexus', 'ES', Decimal('2008'), Decimal('81840.64')),
 (61, 'Mitsubishi', 'Montero', Decimal('2005'), Decimal('80171.93')),
 (62, 'GMC', 'Safari', Decimal('2003'), Decimal('85663.34')),
 (63, 'BMW', '550', Decimal('2006'), Decimal('37612.78')),
 (64, 'Chevrolet', 'Silverado 1500', Decimal('2008'), Decimal('57749.46')),
 (65, 'Ford', 'Mustang', Decimal('1999'), Decimal('67277.68')),
 (66, 'Bentley', 'Azure', Decimal('2008'), Decimal('45465.38')),
 (67, 'BMW', 'X5 M', Decimal('2012'), Decimal('67303.98')),
 (68, 'BMW', 'M3', Decimal('2008'), Decimal('55326.94')),
 (69, 'Ford', 'E-Series', Decimal('2007'), Decimal('63783.70')),
 (70, 'Nissan', 'Pathfinder', Decimal('2005'), Decimal('57449.01')),
 (71, 'Toyota', 'MR2', Decimal('1995'), Decimal('93581.62')),
 (72, 'Alfa Romeo', 'Spider', Decimal('1992'), Decimal('96561.38')),
 (73, 'Nissan', 'Pathfinder', Decimal('1996'), Decimal('63391.19')),
 (74, 'Dodge', 'Ram 1500', Decimal('2000'), Decimal('68056.51')),
 (75, 'Cadillac', 'Escalade', Decimal('2007'), Decimal('40982.32')),
 (76, 'BMW', 'M3', Decimal('2011'), Decimal('65685.46')),
 (77, 'Buick', 'Riviera', Decimal('1995'), Decimal('26887.76')),
 (78, 'Suzuki', 'SJ', Decimal('1994'), Decimal('93949.67')),
 (79, 'Pontiac', 'Grand Am', Decimal('1992'), Decimal('74070.59')),
 (80, 'Suzuki', 'Equator', Decimal('2009'), Decimal('96736.33')),
 (81, 'Honda', 'Civic', Decimal('2003'), Decimal('29926.25')),
 (82, 'Audi', 'A8', Decimal('2002'), Decimal('4019.14')),
 (83, 'Nissan', 'Sentra', Decimal('2010'), Decimal('73412.86')),
 (84, 'Ford', 'F150', Decimal('2012'), Decimal('30461.17')),
 (85, 'Dodge', 'Dakota', Decimal('2000'), Decimal('42199.02')),
 (86, 'Mercedes-Benz', 'SL-Class', Decimal('1994'), Decimal('57799.96')),
 (87, 'Mercury', 'Tracer', Decimal('1989'), Decimal('49059.53')),
 (88, 'Mercedes-Benz', 'S-Class', Decimal('2003'), Decimal('66367.63')),
 (89, 'Land Rover', 'Freelander', Decimal('2002'), Decimal('11117.27')),
 (90, 'Porsche', '928', Decimal('1995'), Decimal('43730.14')),
 (91, 'Dodge', 'Caravan', Decimal('2001'), Decimal('36919.39')),
 (92, 'Plymouth', 'Voyager', Decimal('1993'), Decimal('8026.89')),
 (93, 'Mitsubishi', 'Eclipse', Decimal('1999'), Decimal('75204.19')),
 (94, 'Mercury', 'Cougar', Decimal('1997'), Decimal('19841.43')),
 (95, 'Maserati', 'Karif', Decimal('1989'), Decimal('96701.14')),
 (96, 'Suzuki', 'SJ', Decimal('1986'), Decimal('34292.26')),
 (97, 'Mitsubishi', 'Tundra', Decimal('2009'), Decimal('24099.42')),
 (98, 'Nissan', 'GT-R', Decimal('2013'), Decimal('46794.09')),
 (99, 'Toyota', 'Tacoma', Decimal('2008'), Decimal('61404.74')),
 (100, 'Audi', '200', Decimal('1991'), Decimal('51147.84')),
 (101, 'Buick', 'Coachbuilder', Decimal('1994'), Decimal('97652.40')),
 (102, 'Volvo', 'C70', Decimal('2010'), Decimal('62985.30')),
 (103, 'Toyota', 'Celica', Decimal('2000'), Decimal('48160.43')),
 (104, 'GMC', 'Envoy XL', Decimal('2004'), Decimal('86116.20')),
 (105, 'Chevrolet', 'Corsica', Decimal('1993'), Decimal('28395.00')),
 (106, 'Pontiac', 'Solstice', Decimal('2009'), Decimal('84703.75')),
 (107, 'Ford', 'Crown Victoria', Decimal('2005'), Decimal('57189.55')),
 (108, 'Saab', '9000', Decimal('1997'), Decimal('97292.39')),
 (109, 'Volkswagen', 'Fox', Decimal('1988'), Decimal('81881.19')),
 (110, 'Mazda', 'RX-8', Decimal('2008'), Decimal('22982.61')),
 (111, 'Toyota', 'Prius Plug-in', Decimal('2012'), Decimal('54837.74')),
 (112, 'Toyota', 'Camry', Decimal('2000'), Decimal('75375.73')),
 (113, 'Porsche', 'Cayman', Decimal('2010'), Decimal('4841.21')),
 (114, 'Mercedes-Benz', '300TE', Decimal('1993'), Decimal('29992.01')),
 (115, 'Mercury', 'Cougar', Decimal('1987'), Decimal('76948.82')),
 (116, 'Hyundai', 'Elantra', Decimal('2012'), Decimal('26898.10')),
 (117, 'Maserati', 'Biturbo', Decimal('1984'), Decimal('82492.78')),
 (118, 'Mitsubishi', 'Galant', Decimal('1991'), Decimal('28444.63')),
 (119, 'Chevrolet', 'G-Series 3500', Decimal('1998'), Decimal('18986.81')),
 (120, 'Oldsmobile', 'Aurora', Decimal('2003'), Decimal('52074.76')),
 (121, 'Dodge', 'Ram 1500', Decimal('2010'), Decimal('32880.57')),
 (122, 'Ford', 'Econoline E250', Decimal('1995'), Decimal('54167.36')),
 (123, 'Lexus', 'GX', Decimal('2008'), Decimal('66979.20')),
 (124, 'Mitsubishi', 'Lancer', Decimal('2009'), Decimal('97172.00')),
 (125, 'Mitsubishi', 'Cordia', Decimal('1988'), Decimal('87156.94')),
 (126, 'Chrysler', '300', Decimal('2011'), Decimal('64438.94')),
 (127, 'Porsche', '924 S', Decimal('1987'), Decimal('58490.97')),
 (128, 'Chevrolet', 'Aveo', Decimal('2008'), Decimal('43657.21')),
 (129, 'Volkswagen', 'Cabriolet', Decimal('1993'), Decimal('94356.50')),
 (130, 'Chrysler', '300', Decimal('2011'), Decimal('99208.15')),
 (131, 'Ford', 'Tempo', Decimal('1987'), Decimal('36050.02')),
 (132, 'Volkswagen', 'GTI', Decimal('2011'), Decimal('19143.10')),
 (133, 'Mazda', 'Protege', Decimal('1998'), Decimal('30828.48')),
 (134, 'Ford', 'Expedition EL', Decimal('2008'), Decimal('43791.10')),
 (135, 'Geo', 'Prizm', Decimal('1992'), Decimal('46037.21')),
 (136, 'Buick', 'Enclave', Decimal('2008'), Decimal('34290.20')),
 (137, 'Mitsubishi', 'RVR', Decimal('1994'), Decimal('73775.37')),
 (138, 'Volvo', '940', Decimal('1994'), Decimal('8297.01')),
 (139, 'BMW', '750', Decimal('2006'), Decimal('92183.21')),
 (140, 'Mitsubishi', 'Pajero', Decimal('1989'), Decimal('22419.85')),
 (141, 'GMC', 'Savana 1500', Decimal('1999'), Decimal('75303.79')),
 (142, 'Ford', 'Windstar', Decimal('1999'), Decimal('73264.18')),
 (143, 'Nissan', 'Rogue', Decimal('2012'), Decimal('21280.34')),
 (144, 'Ford', 'Expedition', Decimal('2004'), Decimal('16781.91')),
 (145, 'Dodge', 'Caravan', Decimal('2011'), Decimal('70392.53')),
 (146, 'Pontiac', 'Grand Prix Turbo', Decimal('1990'), Decimal('91429.31')),
 (147, 'Ford', 'Thunderbird', Decimal('1977'), Decimal('7653.10')),
 (148, 'Dodge', 'Ram 1500', Decimal('1997'), Decimal('14018.60')),
 (149, 'Dodge', 'Ram 3500', Decimal('2009'), Decimal('83871.73')),
 (150, 'Ford', 'Escort', Decimal('1995'), Decimal('28248.34')),
 (151, 'Pontiac', 'Bonneville', Decimal('2004'), Decimal('31138.76')),
 (152, 'Hummer', 'H1', Decimal('2003'), Decimal('38594.69')),
 (153, 'Mitsubishi', 'Mighty Max', Decimal('1986'), Decimal('34282.79')),
 (154, 'Ford', 'F350', Decimal('2004'), Decimal('39848.15')),
 (155, 'Mazda', 'MPV', Decimal('2002'), Decimal('24479.10')),
 (156, 'Rolls-Royce', 'Ghost', Decimal('2012'), Decimal('43070.93')),
 (157, 'Spyker', 'C8', Decimal('2007'), Decimal('77156.10')),
 (158, 'BMW', 'X6', Decimal('2013'), Decimal('73541.30')),
 (159, 'Hyundai', 'Tucson', Decimal('2006'), Decimal('78510.53')),
 (160, 'Lincoln', 'MKS', Decimal('2012'), Decimal('21830.50')),
 (161, 'Maybach', '62', Decimal('2010'), Decimal('75270.63')),
 (162, 'Dodge', 'Durango', Decimal('2008'), Decimal('77223.84')),
 (163, 'Subaru', 'Brat', Decimal('1987'), Decimal('12667.65')),
 (164, 'Porsche', 'Panamera', Decimal('2013'), Decimal('31190.85')),
 (165, 'Mazda', 'Protege', Decimal('1996'), Decimal('97506.96')),
 (166, 'Chevrolet', 'Silverado 2500', Decimal('2003'), Decimal('29926.61')),
 (167, 'Nissan', 'Maxima', Decimal('2001'), Decimal('74429.33')),
 (168, 'Hyundai', 'Genesis', Decimal('2012'), Decimal('75091.51')),
 (169, 'Hillman', 'Minx Magnificent', Decimal('1950'), Decimal('43395.95')),
 (170, 'Oldsmobile', 'Bravada', Decimal('1999'), Decimal('20064.26')),
 (171, 'Isuzu', 'Rodeo Sport', Decimal('2003'), Decimal('68977.89')),
 (172, 'Buick', 'LeSabre', Decimal('1993'), Decimal('33685.85')),
 (173, 'Audi', 'R8', Decimal('2009'), Decimal('16770.17')),
 (174, 'Chevrolet', 'Tracker', Decimal('2003'), Decimal('57418.23')),
 (175, 'Jeep', 'Liberty', Decimal('2007'), Decimal('58546.05')),
 (176, 'Mazda', 'B-Series', Decimal('2001'), Decimal('46996.52')),
 (177, 'Lincoln', 'MKT', Decimal('2013'), Decimal('90181.36')),
 (178, 'Mitsubishi', 'GTO', Decimal('1992'), Decimal('52849.83')),
 (179, 'Toyota', 'Sienna', Decimal('2009'), Decimal('14524.45')),
 (180, 'Cadillac', 'DTS', Decimal('2008'), Decimal('23656.54')),
 (181, 'Lexus', 'ES', Decimal('1994'), Decimal('16166.85')),
 (182, 'Suzuki', 'XL-7', Decimal('2005'), Decimal('24154.23')),
 (183, 'Ford', 'E150', Decimal('2004'), Decimal('74611.47')),
 (184, 'Volvo', 'S70', Decimal('1998'), Decimal('99819.03')),
 (185,
  'Bentley',
  'Continental Flying Spur',
  Decimal('2006'),
  Decimal('5456.36')),
 (186, 'Kia', 'Rio', Decimal('2003'), Decimal('55574.15')),
 (187, 'Mercedes-Benz', 'C-Class', Decimal('2005'), Decimal('5459.94')),
 (188, 'Pontiac', 'Trans Sport', Decimal('1998'), Decimal('50497.37')),
 (189, 'Pontiac', 'Firebird', Decimal('1987'), Decimal('61726.69')),
 (190, 'Cadillac', 'DeVille', Decimal('1997'), Decimal('11870.43')),
 (191, 'Chevrolet', '2500', Decimal('2000'), Decimal('24328.05')),
 (192, 'Ford', 'Tempo', Decimal('1989'), Decimal('34791.72')),
 (193, 'Toyota', 'Tundra', Decimal('2009'), Decimal('99493.92')),
 (194, 'Chevrolet', 'Corvette', Decimal('1995'), Decimal('35076.56')),
 (195, 'Chrysler', '300', Decimal('2005'), Decimal('30942.17')),
 (196, 'Porsche', 'Boxster', Decimal('2009'), Decimal('64907.75')),
 (197, 'Ford', 'Ranger', Decimal('2010'), Decimal('28699.92')),
 (198, 'Toyota', 'Sienna', Decimal('1999'), Decimal('89560.14')),
 (199, 'BMW', 'X5', Decimal('2011'), Decimal('43735.99')),
 (200, 'Subaru', 'Impreza', Decimal('1997'), Decimal('29943.66')),
 (201, 'Lexus', 'ES', Decimal('2010'), Decimal('37100.96')),
 (202, 'Ford', 'Taurus', Decimal('1995'), Decimal('71604.50')),
 (203, 'Mercedes-Benz', '190E', Decimal('1992'), Decimal('49329.96')),
 (204, 'Chevrolet', 'Lumina', Decimal('2001'), Decimal('38212.31')),
 (205, 'Mercury', 'Capri', Decimal('1994'), Decimal('42239.24')),
 (206, 'Dodge', 'Charger', Decimal('2008'), Decimal('4682.43')),
 (207, 'Eagle', 'Summit', Decimal('1992'), Decimal('44075.07')),
 (208, 'Dodge', 'Aries', Decimal('1981'), Decimal('42514.07')),
 (209, 'Mitsubishi', 'Eclipse', Decimal('2010'), Decimal('90595.02')),
 (210, 'Chevrolet', 'Lumina', Decimal('1994'), Decimal('70150.76')),
 (211, 'Lincoln', 'Navigator', Decimal('1998'), Decimal('67809.63')),
 (212, 'Acura', 'RSX', Decimal('2004'), Decimal('91822.14')),
 (213, 'Infiniti', 'M', Decimal('2007'), Decimal('99239.49')),
 (214, 'Hummer', 'H2', Decimal('2003'), Decimal('74137.54')),
 (215, 'Mercedes-Benz', 'CL-Class', Decimal('2006'), Decimal('89015.36')),
 (216, 'Lotus', 'Elan', Decimal('1991'), Decimal('82495.62')),
 (217, 'Nissan', '200SX', Decimal('1998'), Decimal('31048.50')),
 (218, 'Aston Martin', 'Vanquish S', Decimal('2006'), Decimal('78112.45')),
 (219, 'Dodge', 'Stratus', Decimal('2000'), Decimal('98322.84')),
 (220, 'Chevrolet', 'Camaro', Decimal('1970'), Decimal('84051.62')),
 (221, 'Toyota', 'Paseo', Decimal('1996'), Decimal('58390.15')),
 (222, 'Smart', 'Fortwo', Decimal('2009'), Decimal('95554.69')),
 (223, 'Mitsubishi', 'Montero Sport', Decimal('2004'), Decimal('5659.86')),
 (224, 'Chevrolet', 'Corvette', Decimal('1963'), Decimal('74507.42')),
 (225, 'Mitsubishi', 'Mirage', Decimal('1999'), Decimal('82789.10')),
 (226, 'Ford', 'Windstar', Decimal('1999'), Decimal('24793.75')),
 (227, 'Volkswagen', 'New Beetle', Decimal('2006'), Decimal('10728.48')),
 (228, 'Ford', 'F350', Decimal('2000'), Decimal('91853.58')),
 (229, 'Acura', 'NSX', Decimal('2000'), Decimal('48274.73')),
 (230, 'Honda', 'Prelude', Decimal('1992'), Decimal('48859.78')),
 (231, 'Suzuki', 'Vitara', Decimal('2001'), Decimal('40708.55')),
 (232, 'Volkswagen', 'Passat', Decimal('2002'), Decimal('61755.96')),
 (233, 'Nissan', 'Xterra', Decimal('2001'), Decimal('43932.55')),
 (234, 'Chevrolet', 'Lumina', Decimal('1994'), Decimal('84781.43')),
 (235, 'Dodge', 'Viper RT/10', Decimal('1994'), Decimal('85368.18')),
 (236, 'Cadillac', 'STS-V', Decimal('2006'), Decimal('19488.30')),
 (237, 'Ford', 'Expedition', Decimal('2001'), Decimal('35154.49')),
 (238, 'Mazda', 'Mazda6 Sport', Decimal('2006'), Decimal('47337.77')),
 (239, 'Mazda', '626', Decimal('1988'), Decimal('50594.48')),
 (240, 'Chevrolet', 'Suburban 1500', Decimal('2009'), Decimal('37197.42')),
 (241, 'Acura', 'TL', Decimal('1996'), Decimal('63800.48')),
 (242, 'Hyundai', 'HED-5', Decimal('2012'), Decimal('82554.14')),
 (243, 'BMW', 'M5', Decimal('2000'), Decimal('78684.32')),
 (244, 'Mazda', 'Miata MX-5', Decimal('1994'), Decimal('38073.64')),
 (245, 'Ford', 'F250', Decimal('1993'), Decimal('49907.81')),
 (246, 'Isuzu', 'Rodeo', Decimal('2003'), Decimal('63085.32')),
 (247, 'Chevrolet', 'Impala', Decimal('2012'), Decimal('77010.92')),
 (248, 'Land Rover', 'Defender', Decimal('1993'), Decimal('39431.68')),
 (249, 'Mercedes-Benz', 'E-Class', Decimal('1986'), Decimal('60939.69')),
 (250, 'Volkswagen', 'rio', Decimal('2002'), Decimal('18877.04')),
 (251, 'Aston Martin', 'Vantage', Decimal('2011'), Decimal('34523.13')),
 (252, 'Toyota', 'RAV4', Decimal('2012'), Decimal('88659.02')),
 (253, 'Chevrolet', 'G-Series 1500', Decimal('1997'), Decimal('43564.54')),
 (254, 'Ford', 'F-Series', Decimal('1987'), Decimal('99829.27')),
 (255, 'Audi', 'A5', Decimal('2012'), Decimal('26332.90')),
 (256, 'Land Rover', 'Discovery', Decimal('2010'), Decimal('43859.16')),
 (257, 'Mercedes-Benz', 'CLK-Class', Decimal('1998'), Decimal('77264.66')),
 (258, 'Lexus', 'LX', Decimal('2000'), Decimal('86301.13')),
 (259, 'Oldsmobile', 'Intrigue', Decimal('2002'), Decimal('94938.28')),
 (260, 'Dodge', 'Viper', Decimal('2002'), Decimal('98975.62')),
 (261, 'Volkswagen', 'Passat', Decimal('1998'), Decimal('41022.52')),
 (262, 'Dodge', 'Caravan', Decimal('1985'), Decimal('61132.91')),
 (263, 'Audi', 'A6', Decimal('2005'), Decimal('16697.45')),
 (264, 'Chevrolet', 'Silverado 2500', Decimal('2006'), Decimal('57995.66')),
 (265, 'Acura', 'RL', Decimal('2004'), Decimal('77861.87')),
 (266, 'Chrysler', '300M', Decimal('2001'), Decimal('34522.44')),
 (267, 'Mazda', 'Mazda6', Decimal('2007'), Decimal('19492.09')),
 (268, 'Volkswagen', 'Jetta', Decimal('1999'), Decimal('20028.32')),
 (269, 'Ford', 'E250', Decimal('2012'), Decimal('45309.39')),
 (270, 'GMC', 'Jimmy', Decimal('1993'), Decimal('82341.63')),
 (271, 'Saab', '900', Decimal('1997'), Decimal('55764.90')),
 (272, 'Oldsmobile', '98', Decimal('1994'), Decimal('88329.89')),
 (273, 'Nissan', 'Maxima', Decimal('1993'), Decimal('37402.69')),
 (274, 'Mercury', 'Tracer', Decimal('1997'), Decimal('49365.25')),
 (275, 'Suzuki', 'Reno', Decimal('2008'), Decimal('59051.33')),
 (276, 'Mitsubishi', 'Lancer Evolution', Decimal('2002'), Decimal('46756.33')),
 (277, 'Toyota', 'RAV4', Decimal('2011'), Decimal('58184.60')),
 (278, 'Jeep', 'Grand Cherokee', Decimal('1996'), Decimal('17929.07')),
 (279, 'Volvo', 'XC90', Decimal('2003'), Decimal('61967.24')),
 (280, 'Mercedes-Benz', 'Sprinter 2500', Decimal('2012'), Decimal('65279.03')),
 (281, 'Nissan', '350Z Roadster', Decimal('2006'), Decimal('37452.22')),
 (282, 'Mazda', 'Miata MX-5', Decimal('2009'), Decimal('79053.64')),
 (283, 'Mitsubishi', 'GTO', Decimal('1992'), Decimal('48699.67')),
 (284, 'Chevrolet', 'Cruze', Decimal('2013'), Decimal('59554.84')),
 (285, 'Oldsmobile', 'Toronado', Decimal('1966'), Decimal('18200.02')),
 (286, 'Suzuki', 'Cultus', Decimal('1985'), Decimal('82912.84')),
 (287, 'Mazda', 'RX-8', Decimal('2009'), Decimal('44908.27')),
 (288, 'Honda', 'Pilot', Decimal('2008'), Decimal('54708.17')),
 (289, 'Audi', 'A3', Decimal('2009'), Decimal('70811.01')),
 (290, 'Honda', 'Prelude', Decimal('1998'), Decimal('68623.99')),
 (291, 'Volvo', '960', Decimal('1995'), Decimal('75091.63')),
 (292, 'Isuzu', 'Hombre', Decimal('2000'), Decimal('65521.58')),
 (293, 'Mazda', 'Mazda5', Decimal('2008'), Decimal('69640.72')),
 (294, 'Lexus', 'ES', Decimal('1991'), Decimal('29788.76')),
 (295, 'Buick', 'Somerset', Decimal('1986'), Decimal('57287.29')),
 (296, 'Saab', '900', Decimal('1994'), Decimal('87801.66')),
 (297, 'Chevrolet', 'Corvette', Decimal('1997'), Decimal('68564.74')),
 (298, 'Mitsubishi', 'Pajero', Decimal('1999'), Decimal('62842.50')),
 (299, 'Infiniti', 'G', Decimal('2010'), Decimal('48826.29')),
 (300, 'Chevrolet', 'Corvette', Decimal('1999'), Decimal('83018.03')),

In [292]:
cursor1.execute("SELECT make FROM car;")
print(cursor1.fetchall())

[('Chevrolet',),
 ('Toyota',),
 ('Lexus',),
 ('Dodge',),
 ('Mitsubishi',),
 ('Lexus',),
 ('Porsche',),
 ('Subaru',),
 ('GMC',),
 ('Mitsubishi',),
 ('GMC',),
 ('GMC',),
 ('GMC',),
 ('Toyota',),
 ('Honda',),
 ('Lexus',),
 ('Buick',),
 ('Mazda',),
 ('Pontiac',),
 ('Mercedes-Benz',),
 ('Buick',),
 ('Ford',),
 ('Mitsubishi',),
 ('Audi',),
 ('Kia',),
 ('Audi',),
 ('Lincoln',),
 ('Porsche',),
 ('Chevrolet',),
 ('Subaru',),
 ('Ford',),
 ('Dodge',),
 ('Toyota',),
 ('Oldsmobile',),
 ('Ford',),
 ('Toyota',),
 ('Dodge',),
 ('Kia',),
 ('Hyundai',),
 ('Lamborghini',),
 ('BMW',),
 ('Dodge',),
 ('Chrysler',),
 ('Mercedes-Benz',),
 ('Mitsubishi',),
 ('Mercedes-Benz',),
 ('Maserati',),
 ('Kia',),
 ('Lexus',),
 ('Chevrolet',),
 ('Mitsubishi',),
 ('Chevrolet',),
 ('Ford',),
 ('Ford',),
 ('Lotus',),
 ('Mazda',),
 ('Chevrolet',),
 ('Jaguar',),
 ('Mercedes-Benz',),
 ('Lexus',),
 ('Mitsubishi',),
 ('GMC',),
 ('BMW',),
 ('Chevrolet',),
 ('Ford',),
 ('Bentley',),
 ('BMW',),
 ('BMW',),
 ('Ford',),
 ('Nissan',),
 ('Toyota',),
 ('Alfa Romeo',),
 ('Nissan',),
 ('Dodge',),
 ('Cadillac',),
 ('BMW',),
 ('Buick',),
 ('Suzuki',),
 ('Pontiac',),
 ('Suzuki',),
 ('Honda',),
 ('Audi',),
 ('Nissan',),
 ('Ford',),
 ('Dodge',),
 ('Mercedes-Benz',),
 ('Mercury',),
 ('Mercedes-Benz',),
 ('Land Rover',),
 ('Porsche',),
 ('Dodge',),
 ('Plymouth',),
 ('Mitsubishi',),
 ('Mercury',),
 ('Maserati',),
 ('Suzuki',),
 ('Mitsubishi',),
 ('Nissan',),
 ('Toyota',),
 ('Audi',),
 ('Buick',),
 ('Volvo',),
 ('Toyota',),
 ('GMC',),
 ('Chevrolet',),
 ('Pontiac',),
 ('Ford',),
 ('Saab',),
 ('Volkswagen',),
 ('Mazda',),
 ('Toyota',),
 ('Toyota',),
 ('Porsche',),
 ('Mercedes-Benz',),
 ('Mercury',),
 ('Hyundai',),
 ('Maserati',),
 ('Mitsubishi',),
 ('Chevrolet',),
 ('Oldsmobile',),
 ('Dodge',),
 ('Ford',),
 ('Lexus',),
 ('Mitsubishi',),
 ('Mitsubishi',),
 ('Chrysler',),
 ('Porsche',),
 ('Chevrolet',),
 ('Volkswagen',),
 ('Chrysler',),
 ('Ford',),
 ('Volkswagen',),
 ('Mazda',),
 ('Ford',),
 ('Geo',),
 ('Buick',),
 ('Mitsubishi',),
 ('Volvo',),
 ('BMW',),
 ('Mitsubishi',),
 ('GMC',),
 ('Ford',),
 ('Nissan',),
 ('Ford',),
 ('Dodge',),
 ('Pontiac',),
 ('Ford',),
 ('Dodge',),
 ('Dodge',),
 ('Ford',),
 ('Pontiac',),
 ('Hummer',),
 ('Mitsubishi',),
 ('Ford',),
 ('Mazda',),
 ('Rolls-Royce',),
 ('Spyker',),
 ('BMW',),
 ('Hyundai',),
 ('Lincoln',),
 ('Maybach',),
 ('Dodge',),
 ('Subaru',),
 ('Porsche',),
 ('Mazda',),
 ('Chevrolet',),
 ('Nissan',),
 ('Hyundai',),
 ('Hillman',),
 ('Oldsmobile',),
 ('Isuzu',),
 ('Buick',),
 ('Audi',),
 ('Chevrolet',),
 ('Jeep',),
 ('Mazda',),
 ('Lincoln',),
 ('Mitsubishi',),
 ('Toyota',),
 ('Cadillac',),
 ('Lexus',),
 ('Suzuki',),
 ('Ford',),
 ('Volvo',),
 ('Bentley',),
 ('Kia',),
 ('Mercedes-Benz',),
 ('Pontiac',),
 ('Pontiac',),
 ('Cadillac',),
 ('Chevrolet',),
 ('Ford',),
 ('Toyota',),
 ('Chevrolet',),
 ('Chrysler',),
 ('Porsche',),
 ('Ford',),
 ('Toyota',),
 ('BMW',),
 ('Subaru',),
 ('Lexus',),
 ('Ford',),
 ('Mercedes-Benz',),
 ('Chevrolet',),
 ('Mercury',),
 ('Dodge',),
 ('Eagle',),
 ('Dodge',),
 ('Mitsubishi',),
 ('Chevrolet',),
 ('Lincoln',),
 ('Acura',),
 ('Infiniti',),
 ('Hummer',),
 ('Mercedes-Benz',),
 ('Lotus',),
 ('Nissan',),
 ('Aston Martin',),
 ('Dodge',),
 ('Chevrolet',),
 ('Toyota',),
 ('Smart',),
 ('Mitsubishi',),
 ('Chevrolet',),
 ('Mitsubishi',),
 ('Ford',),
 ('Volkswagen',),
 ('Ford',),
 ('Acura',),
 ('Honda',),
 ('Suzuki',),
 ('Volkswagen',),
 ('Nissan',),
 ('Chevrolet',),
 ('Dodge',),
 ('Cadillac',),
 ('Ford',),
 ('Mazda',),
 ('Mazda',),
 ('Chevrolet',),
 ('Acura',),
 ('Hyundai',),
 ('BMW',),
 ('Mazda',),
 ('Ford',),
 ('Isuzu',),
 ('Chevrolet',),
 ('Land Rover',),
 ('Mercedes-Benz',),
 ('Volkswagen',),
 ('Aston Martin',),
 ('Toyota',),
 ('Chevrolet',),
 ('Ford',),
 ('Audi',),
 ('Land Rover',),
 ('Mercedes-Benz',),
 ('Lexus',),
 ('Oldsmobile',),
 ('Dodge',),
 ('Volkswagen',),
 ('Dodge',),
 ('Audi',),
 ('Chevrolet',),
 ('Acura',),
 ('Chrysler',),
 ('Mazda',),
 ('Volkswagen',),
 ('Ford',),
 ('GMC',),
 ('Saab',),
 ('Oldsmobile',),
 ('Nissan',),
 ('Mercury',),
 ('Suzuki',),
 ('Mitsubishi',),
 ('Toyota',),
 ('Jeep',),
 ('Volvo',),
 ('Mercedes-Benz',),
 ('Nissan',),
 ('Mazda',),
 ('Mitsubishi',),
 ('Chevrolet',),
 ('Oldsmobile',),
 ('Suzuki',),
 ('Mazda',),
 ('Honda',),
 ('Audi',),
 ('Honda',),
 ('Volvo',),
 ('Isuzu',),
 ('Mazda',),
 ('Lexus',),
 ('Buick',),
 ('Saab',),
 ('Chevrolet',),
 ('Mitsubishi',),
 ('Infiniti',),
 ('Chevrolet',),
 ('Pontiac',),
 ('Acura',),
 ('Honda',),
 ('Dodge',),
 ('Lincoln',),
 ('BMW',),
 ('BMW',),
 ('BMW',),
 ('Chevrolet',),
 ('Chevrolet',),
 ('Pontiac',),
 ('Chevrolet',),
 ('Pontiac',),
 ('Volkswagen',),
 ('Ford',),
 ('Dodge',),
 ('Ford',),
 ('Chevrolet',),
 ('Acura',),
 ('Volkswagen',),
 ('Mercedes-Benz',),
 ('Chrysler',),
 ('Mazda',),
 ('Suzuki',),
 ('Pontiac',),
 ('Chevrolet',),
 ('Infiniti',),
 ('GMC',),
 ('Volkswagen',),
 ('Mazda',),
 ('Chevrolet',),
 ('Nissan',),
 ('Chevrolet',),
 ('Mazda',),
 ('Mercury',),
 ('Saturn',),
 ('GMC',),
 ('Mercedes-Benz',),
 ('Infiniti',),
 ('Audi',),
 ('Dodge',),
 ('GMC',),
 ('Mercedes-Benz',),
 ('Honda',),
 ('GMC',),
 ('Infiniti',),
 ('Lincoln',),
 ('Acura',),
 ('Chevrolet',),
 ('Lincoln',),
 ('Kia',),
 ('Mazda',),
 ('Lexus',),
 ('Dodge',),
 ('Honda',),
 ('Maserati',),
 ('Infiniti',),
 ('Lincoln',),
 ('Ford',),
 ('Saab',),
 ('Ford',),
 ('Jaguar',),
 ('Hyundai',),
 ('Dodge',),
 ('Mercedes-Benz',),
 ('Mitsubishi',),
 ('Ford',),
 ('Mitsubishi',),
 ('Oldsmobile',),
 ('Mercedes-Benz',),
 ('GMC',),
 ('Honda',),
 ('Toyota',),
 ('Volvo',),
 ('Toyota',),
 ('Volkswagen',),
 ('Dodge',),
 ('BMW',),
 ('Lamborghini',),
 ('Cadillac',),
 ('Toyota',),
 ('Land Rover',),
 ('Plymouth',),
 ('Mercedes-Benz',),
 ('Scion',),
 ('GMC',),
 ('Buick',),
 ('Volvo',),
 ('Chevrolet',),
 ('Honda',),
 ('Mercedes-Benz',),
 ('Ford',),
 ('Lincoln',),
 ('Lexus',),
 ('Dodge',),
 ('Audi',),
 ('Aston Martin',),
 ('Chrysler',),
 ('Saab',),
 ('Buick',),
 ('Chevrolet',),
 ('Chevrolet',),
 ('Subaru',),
 ('Honda',),
 ('Toyota',),
 ('GMC',),
 ('Mercedes-Benz',),
 ('Plymouth',),
 ('Chevrolet',),
 ('Cadillac',),
 ('Ford',),
 ('Chevrolet',),
 ('Lincoln',),
 ('Chevrolet',),
 ('Mitsubishi',),
 ('Chevrolet',),
 ('Volkswagen',),
 ('Suzuki',),
 ('Aston Martin',),
 ('Dodge',),
 ('Volvo',),
 ('Subaru',),
 ('Lotus',),
 ('Ford',),
 ('Hyundai',),
 ('Aptera',),
 ('Chevrolet',),
 ('Chevrolet',),
 ('Chevrolet',),
 ('Chevrolet',),
 ('Toyota',),
 ('Dodge',),
 ('Buick',),
 ('Volkswagen',),
 ('Mazda',),
 ('Isuzu',),
 ('Kia',),
 ('BMW',),
 ('Mazda',),
 ('Audi',),
 ('Mercedes-Benz',),
 ('Porsche',),
 ('Mitsubishi',),
 ('Ford',),
 ('BMW',),
 ('Toyota',),
 ('Infiniti',),
 ('Chevrolet',),
 ('Ford',),
 ('Land Rover',),
 ('Aston Martin',),
 ('Cadillac',),
 ('Volkswagen',),
 ('Mazda',),
 ('Hyundai',),
 ('Mitsubishi',),
 ('Chevrolet',),
 ('BMW',),
 ('GMC',),
 ('Honda',),
 ('Jaguar',),
 ('Chevrolet',),
 ('Ford',),
 ('Cadillac',),
 ('Jeep',),
 ('Lexus',),
 ('GMC',),
 ('Chevrolet',),
 ('Nissan',),
 ('Mercury',),
 ('Honda',),
 ('Nissan',),
 ('Nissan',),
 ('Ford',),
 ('Daewoo',),
 ('Cadillac',),
 ('Buick',),
 ('Nissan',),
 ('Mercury',),
 ('Jeep',),
 ('Ford',),
 ('Chevrolet',),
 ('Toyota',),
 ('Nissan',),
 ('Hyundai',),
 ('Lexus',),
 ('Acura',),
 ('Mercedes-Benz',),
 ('Mercedes-Benz',),
 ('Cadillac',),
 ('Acura',),
 ('Chevrolet',),
 ('Mercedes-Benz',),
 ('Kia',),
 ('Mercedes-Benz',),
 ('Plymouth',),
 ('Mercedes-Benz',),
 ('Saturn',),
 ('Toyota',),
 ('Audi',),
 ('GMC',),
 ('Hyundai',),
 ('Acura',),
 ('Chevrolet',),
 ('Plymouth',),
 ('Mercedes-Benz',),
 ('Mercedes-Benz',),
 ('Acura',),
 ('Geo',),
 ('Mazda',),
 ('Jeep',),
 ('Aston Martin',),
 ('Volkswagen',),
 ('Nissan',),
 ('Pontiac',),
 ('Suzuki',),
 ('Infiniti',),
 ('Audi',),
 ('Honda',),
 ('GMC',),
 ('Kia',),
 ('Mercury',),
 ('Lexus',),
 ('Volkswagen',),
 ('Mercury',),
 ('Chevrolet',),
 ('Ford',),
 ('BMW',),
 ('Volvo',),
 ('Nissan',),
 ('Oldsmobile',),
 ('Ford',),
 ('Chevrolet',),
 ('Hyundai',),
 ('Smart',),
 ('Mitsubishi',),
 ('Pontiac',),
 ('Toyota',),
 ('Ford',),
 ('GMC',),
 ('Mitsubishi',),
 ('Plymouth',),
 ('Volvo',),
 ('Infiniti',),
 ('Ford',),
 ('Dodge',),
 ('Toyota',),
 ('Chevrolet',),
 ('Hyundai',),
 ('Ford',),
 ('Mercedes-Benz',),
 ('Mercedes-Benz',),
 ('Ford',),
 ('Ford',),
 ('Mercury',),
 ('Kia',),
 ('Subaru',),
 ('Honda',),
 ('Mercedes-Benz',),
 ('Buick',),
 ('Lincoln',),
 ('Chevrolet',),
 ('Ford',),
 ('Daewoo',),
 ('GMC',),
 ('Hyundai',),
 ('Hyundai',),
 ('Mazda',),
 ('Ford',),
 ('Infiniti',),
 ('Saab',),
 ('Chevrolet',),
 ('Toyota',),
 ('Lexus',),
 ('Lexus',),
 ('Aston Martin',),
 ('Acura',),
 ('Volkswagen',),
 ('Ford',),
 ('GMC',),
 ('Acura',),
 ('Audi',),
 ('Ford',),
 ('Ford',),
 ('Mercury',),
 ('GMC',),
 ('BMW',),
 ('Oldsmobile',),
 ('GMC',),
 ('Ford',),
 ('Mitsubishi',),
 ('Porsche',),
 ('Lexus',),
 ('Dodge',),
 ('Chevrolet',),
 ('Buick',),
 ('GMC',),
 ('Lincoln',),
 ('Audi',),
 ('Mazda',),
 ('Oldsmobile',),
 ('Volkswagen',),
 ('BMW',),
 ('Holden',),
 ('Smart',),
 ('Volkswagen',),
 ('Lexus',),
 ('Maybach',),
 ('Ford',),
 ('Toyota',),
 ('Mitsubishi',),
 ('Ford',),
 ('Ford',),
 ('Cadillac',),
 ('Lexus',),
 ('Plymouth',),
 ('Mitsubishi',),
 ('Audi',),
 ('Suzuki',),
 ('Oldsmobile',),
 ('Buick',),
 ('Audi',),
 ('Ford',),
 ('Nissan',),
 ('BMW',),
 ('Ford',),
 ('Chevrolet',),
 ('BMW',),
 ('Chevrolet',),
 ('Toyota',),
 ('Mercedes-Benz',),
 ('Chevrolet',),
 ('Acura',),
 ('Mitsubishi',),
 ('Isuzu',),
 ('Kia',),
 ('BMW',),
 ('Nissan',),
 ('Mercedes-Benz',),
 ('Toyota',),
 ('Chrysler',),
 ('Jeep',),
 ('Lexus',),
 ('Lexus',),
 ('Subaru',),
 ('Toyota',),
 ('Ford',),
 ('Mazda',),
 ('Mercedes-Benz',),
 ('Maserati',),
 ('Suzuki',),
 ('Chevrolet',),
 ('Dodge',),
 ('Ford',),
 ('Saab',),
 ('Volvo',),
 ('Dodge',),
 ('Suzuki',),
 ('Buick',),
 ('Subaru',),
 ('Mitsubishi',),
 ('Volkswagen',),
 ('Lexus',),
 ('Ford',),
 ('Toyota',),
 ('Mitsubishi',),
 ('Subaru',),
 ('Maserati',),
 ('Mazda',),
 ('Ford',),
 ('Ford',),
 ('Honda',),
 ('Lincoln',),
 ('Hyundai',),
 ('Subaru',),
 ('Dodge',),
 ('Lexus',),
 ('Mercury',),
 ('Dodge',),
 ('Hyundai',),
 ('Pontiac',),
 ('Nissan',),
 ('Audi',),
 ('Buick',),
 ('Chevrolet',),
 ('Ford',),
 ('Porsche',),
 ('BMW',),
 ('Chevrolet',),
 ('Infiniti',),
 ('Cadillac',),
 ('Chevrolet',),
 ('Mercedes-Benz',),
 ('Cadillac',),
 ('Lexus',),
 ('Oldsmobile',),
 ('Dodge',),
 ('Buick',),
 ('Hyundai',),
 ('Dodge',),
 ('Saturn',),
 ('Mercury',),
 ('Ford',),
 ('Lexus',),
 ('Ford',),
 ('Volkswagen',),
 ('Chevrolet',),
 ('Chevrolet',),
 ('Buick',),
 ('Lincoln',),
 ('Suzuki',),
 ('Volkswagen',),
 ('Mazda',),
 ('Toyota',),
 ('Honda',),
 ('Mitsubishi',),
 ('Aston Martin',),
 ('Honda',),
 ('Lotus',),
 ('Ford',),
 ('Toyota',),
 ('Toyota',),
 ('GMC',),
 ('Lexus',),
 ('Acura',),
 ('Dodge',),
 ('Honda',),
 ('Mazda',),
 ('Ford',),
 ('Lincoln',),
 ('Chevrolet',),
 ('Ford',),
 ('Ford',),
 ('Mercedes-Benz',),
 ('Acura',),
 ('Dodge',),
 ('Dodge',),
 ('Nissan',),
 ('Isuzu',),
 ('Ferrari',),
 ('Chevrolet',),
 ('Chevrolet',),
 ('Buick',),
 ('Chevrolet',),
 ('Volkswagen',),
 ('Mitsubishi',),
 ('Pontiac',),
 ('Dodge',),
 ('Honda',),
 ('Bentley',),
 ('Plymouth',),
 ('Toyota',),
 ('Scion',),
 ('Chevrolet',),
 ('Toyota',),
 ('Suzuki',),
 ('Chrysler',),
 ('Ford',),
 ('Mitsubishi',),
 ('Ford',),
 ('Toyota',),
 ('Chrysler',),
 ('Ford',),
 ('Buick',),
 ('MINI',),
 ('Volkswagen',),
 ('Chevrolet',),
 ('Oldsmobile',),
 ('Honda',),
 ('Lotus',),
 ('Jeep',),
 ('GMC',),
 ('Chrysler',),
 ('Ford',),
 ('Mercedes-Benz',),
 ('Mazda',),
 ('Dodge',),
 ('Audi',),
 ('Pontiac',),
 ('Land Rover',),
 ('Volkswagen',),
 ('Maserati',),
 ('Mitsubishi',),
 ('Mitsubishi',),
 ('Mazda',),
 ('Chrysler',),
 ('Isuzu',),
 ('Pontiac',),
 ('BMW',),
 ('GMC',),
 ('Lexus',),
 ('Suzuki',),
 ('Ford',),
 ('Dodge',),
 ('Audi',),
 ('Ford',),
 ('Pontiac',),
 ('Ford',),
 ('Ford',),
 ('Cadillac',),
 ('BMW',),
 ('Ford',),
 ('Honda',),
 ('Land Rover',),
 ('Toyota',),
 ('Ford',),
 ('Lexus',),
 ('Maserati',),
 ('Ford',),
 ('Lexus',),
 ('Honda',),
 ('Ford',),
 ('Jaguar',),
 ('Suzuki',),
 ('Mercedes-Benz',),
 ('Jeep',),
 ('Chevrolet',),
 ('Mazda',),
 ('Porsche',),
 ('Ford',),
 ('Toyota',),
 ('Mitsubishi',),
 ('Toyota',),
 ('Volkswagen',),
 ('Saab',),
 ('Ford',),
 ('Ford',),
 ('GMC',),
 ('Toyota',),
 ('Toyota',),
 ('Mercedes-Benz',),
 ('Mercedes-Benz',),
 ('GMC',),
 ('Chevrolet',),
 ('Infiniti',),
 ('Volvo',),
 ('Oldsmobile',),
 ('Volkswagen',),
 ('Dodge',),
 ('Acura',),
 ('GMC',),
 ('Dodge',),
 ('Acura',),
 ('Chevrolet',),
 ('Chevrolet',),
 ('Ford',),
 ('Dodge',),
 ('Nissan',),
 ('Acura',),
 ('Ford',),
 ('Mercury',),
 ('Dodge',),
 ('Plymouth',),
 ('Holden',),
 ('Toyota',),
 ('GMC',),
 ('Kia',),
 ('Mazda',),
 ('Lexus',),
 ('Dodge',),
 ('Honda',),
 ('Infiniti',),
 ('Lamborghini',),
 ('Mazda',),
 ('Lamborghini',),
 ('Volkswagen',),
 ('Nissan',),
 ('Chevrolet',),
 ('Chevrolet',),
 ('Chevrolet',),
 ('Lotus',),
 ('Saturn',),
 ('Lexus',),
 ('Infiniti',),
 ('Buick',),
 ('Volvo',),
 ('Mazda',),
 ('Lincoln',),
 ('Ford',),
 ('Oldsmobile',),
 ('Mazda',),
 ('Isuzu',),
 ('BMW',),
 ('Dodge',),
 ('Hyundai',),
 ('Toyota',),
 ('Mercury',),
 ('Dodge',),
 ('Lincoln',),
 ('Toyota',),
 ('Audi',),
 ('Dodge',),
 ('Isuzu',),
 ('Honda',),
 ('GMC',),
 ('Volkswagen',),
 ('Bentley',),
 ('Honda',),
 ('Toyota',),
 ('Suzuki',),
 ('Lexus',),
 ('Honda',),
 ('Chevrolet',),
 ('Ford',),
 ('Acura',),
 ('Chevrolet',),
 ('Audi',),
 ('Ford',),
 ('Nissan',),
 ('Volkswagen',),
 ('Lexus',),
 ('Fiat',),
 ('Lincoln',),
 ('Suzuki',),
 ('Chevrolet',),
 ('Land Rover',),
 ('Ford',),
 ('Suzuki',),
 ('Dodge',),
 ('BMW',),
 ('Toyota',),
 ('Toyota',),
 ('Mercury',),
 ('Land Rover',),
 ('Ford',),
 ('Hyundai',),
 ('Bentley',),
 ('Chevrolet',),
 ('Volkswagen',),
 ('Volkswagen',),
 ('Jaguar',),
 ('BMW',),
 ('Nissan',),
 ('Lexus',),
 ('Hyundai',),
 ('Chevrolet',),
 ('Cadillac',),
 ('Cadillac',),
 ('BMW',),
 ('Subaru',),
 ('Lincoln',),
 ('Honda',),
 ('Saab',),
 ('BMW',),
 ('BMW',),
 ('Dodge',),
 ('Lincoln',),
 ('Fillmore',),
 ('Honda',),
 ('Chrysler',),
 ('GMC',),
 ('Chevrolet',),
 ('Dodge',),
 ('Jeep',),
 ('Toyota',),
 ('Nissan',),
 ('Toyota',),
 ('Volvo',),
 ('Suzuki',),
 ('Nissan',),
 ('Mercury',),
 ('Honda',),
 ('Volkswagen',),
 ('Suzuki',),
 ('Dodge',),
 ('Mazda',),
 ('Subaru',),
 ('Volvo',),
 ('Kia',),
 ('Chevrolet',),
 ('Chevrolet',),
 ('Ford',),
 ('Honda',),
 ('Nissan',),
 ('Volkswagen',),
 ('Ford',),
 ('Toyota',),
 ('GMC',),
 ('Mitsubishi',),
 ('Chrysler',),
 ('Chevrolet',),
 ('Toyota',),
 ('Mercedes-Benz',),
 ('Porsche',),
 ('Acura',),
 ('Acura',),
 ('Dodge',),
 ('Chrysler',),
 ('Ram',),
 ('Honda',),
 ('Nissan',),
 ('Dodge',),
 ('Nissan',),
 ('Hummer',),
 ('GMC',),
 ('Chevrolet',),
 ('GMC',),
 ('Chevrolet',),
 ('Kia',),
 ('McLaren',)]

In [293]:
cursor1.execute("SELECT COUNT (*) FROM car")
cursor1.fetchone()

(1000,)

In [294]:
# cursor1.execute("PRAGMA table_info(customers);")
# cursor1.fetchall()

In [295]:
query = "SELECT * FROM car LIMIT 5"
df = pd.read_sql(query, pdb, index_col="id") # CustomerId ustunidan DF Indeksi sifatida foydalanamiz
df

C:\Users\user\AppData\Local\Temp\ipykernel_14312\1700812346.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, pdb, index_col="id") # CustomerId ustunidan DF Indeksi sifatida foydalanamiz

          make         model    year     price
id
1    Chevrolet  G-Series G30  1995.0  56733.89
2       Toyota       4Runner  1996.0  30391.77
3        Lexus            RX  2012.0   6537.82
4        Dodge      Ram 2500  1996.0  48262.84
5   Mitsubishi           GTO  1993.0  70156.81

In [296]:
# customers jadvalidagi barcha mijozlarni ko'rish
query = "SELECT * FROM car"
df = pd.read_sql(query, pdb, index_col="id")
df.sample(5)

C:\Users\user\AppData\Local\Temp\ipykernel_14312\2553625916.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, pdb, index_col="id")

              make     model    year     price
id
86   Mercedes-Benz  SL-Class  1994.0  57799.96
124     Mitsubishi    Lancer  2009.0  97172.00
478         Nissan  Frontier  2003.0  63159.22
304          Dodge  Ram 3500  2010.0  59558.21
115        Mercury    Cougar  1987.0  76948.82

In [297]:
# Jadvalni chaqirishda aynan qaysi ustunlar kerakligini ham ko'rsatishimiz mumkin
query = "SELECT make, model, price FROM car LIMIT 10"
pd.read_sql(query, pdb)

C:\Users\user\AppData\Local\Temp\ipykernel_14312\2167505327.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, pdb)

         make         model     price
0   Chevrolet  G-Series G30  56733.89
1      Toyota       4Runner  30391.77
2       Lexus            RX   6537.82
3       Dodge      Ram 2500  48262.84
4  Mitsubishi           GTO  70156.81
5       Lexus            LS  23342.25
6     Porsche       Boxster  58733.11
7      Subaru        Legacy  54683.40
8         GMC   Savana 3500  90809.33
9  Mitsubishi        Galant  89616.37

In [298]:
# Ma'lumotlarni biror ustun bo'yicha tartiblash
query = "SELECT * FROM car ORDER BY price"
df = pd.read_sql(query, pdb, index_col="id")
df.head(10)

C:\Users\user\AppData\Local\Temp\ipykernel_14312\3185777798.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, pdb, index_col="id")

           make          model    year    price
id
82         Audi             A8  2002.0  4019.14
57    Chevrolet         Camaro  1972.0  4053.14
910  Volkswagen          Jetta  1986.0  4083.32
324      Suzuki       Sidekick  1991.0  4133.61
644       Lexus             LX  2008.0  4152.77
540         GMC          Yukon  2004.0  4162.14
658      Suzuki   Grand Vitara  2000.0  4309.42
641    Chrysler       Concorde  2003.0  4320.24
790         GMC  Suburban 1500  1996.0  4466.90
51   Mitsubishi       Endeavor  2006.0  4640.06

In [299]:
# Ma'lumotlarni biror ustun bo'yicha kamayish tartyibida olish
query = "SELECT * FROM car ORDER BY price DESC"
df = pd.read_sql(query, pdb, index_col="id")
df.head(10)

C:\Users\user\AppData\Local\Temp\ipykernel_14312\3211074635.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, pdb, index_col="id")

         make       model    year     price
id
821    Toyota  Highlander  2008.0  99886.78
517  Infiniti           G  1996.0  99840.87
254      Ford    F-Series  1987.0  99829.27
556       Kia        Soul  2010.0  99821.52
184     Volvo         S70  1998.0  99819.03
193    Toyota      Tundra  2009.0  99493.92
823    Toyota       Camry  2003.0  99405.12
480      Jeep     Patriot  2007.0  99343.48
213  Infiniti           M  2007.0  99239.49
130  Chrysler         300  2011.0  99208.15

In [300]:
query = "SELECT DISTINCT make FROM car"
cursor1.execute(query)
cursor1.fetchall()

[('Fillmore',),
 ('McLaren',),
 ('Ford',),
 ('Smart',),
 ('Maserati',),
 ('Dodge',),
 ('Infiniti',),
 ('MINI',),
 ('Bentley',),
 ('Pontiac',),
 ('Plymouth',),
 ('Holden',),
 ('Audi',),
 ('Lexus',),
 ('Jeep',),
 ('Volvo',),
 ('Acura',),
 ('Cadillac',),
 ('Suzuki',),
 ('Aston Martin',),
 ('Mitsubishi',),
 ('Ferrari',),
 ('Chrysler',),
 ('Isuzu',),
 ('GMC',),
 ('Maybach',),
 ('Lincoln',),
 ('Honda',),
 ('Ram',),
 ('Daewoo',),
 ('Spyker',),
 ('Scion',),
 ('Aptera',),
 ('Chevrolet',),
 ('Saturn',),
 ('Hillman',),
 ('Porsche',),
 ('Alfa Romeo',),
 ('Rolls-Royce',),
 ('Jaguar',),
 ('Lotus',),
 ('Kia',),
 ('Lamborghini',),
 ('Mercedes-Benz',),
 ('Oldsmobile',),
 ('Fiat',),
 ('Land Rover',),
 ('Buick',),
 ('Nissan',),
 ('Saab',),
 ('Hyundai',),
 ('Geo',),
 ('Subaru',),
 ('Mazda',),
 ('BMW',),
 ('Volkswagen',),
 ('Mercury',),
 ('Eagle',),
 ('Hummer',),
 ('Toyota',)]

In [301]:
# natijani DF ko'rinishida olamiz
make = pd.read_sql(query, pdb)
make.head()

C:\Users\user\AppData\Local\Temp\ipykernel_14312\3684167542.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  make = pd.read_sql(query, pdb)

       make
0  Fillmore
1   McLaren
2      Ford
3     Smart
4  Maserati

In [302]:
obj = make['make']
print(obj)

0          Fillmore
1           McLaren
2              Ford
3             Smart
4          Maserati
5             Dodge
6          Infiniti
7              MINI
8           Bentley
9           Pontiac
10         Plymouth
11           Holden
12             Audi
13            Lexus
14             Jeep
15            Volvo
16            Acura
17         Cadillac
18           Suzuki
19     Aston Martin
20       Mitsubishi
21          Ferrari
22         Chrysler
23            Isuzu
24              GMC
25          Maybach
26          Lincoln
27            Honda
28              Ram
29           Daewoo
30           Spyker
31            Scion
32           Aptera
33        Chevrolet
34           Saturn
35          Hillman
36          Porsche
37       Alfa Romeo
38      Rolls-Royce
39           Jaguar
40            Lotus
41              Kia
42      Lamborghini
43    Mercedes-Benz
44       Oldsmobile
45             Fiat
46       Land Rover
47            Buick
48           Nissan
49             Saab
50          Hyundai
51              Geo
52           Subaru
53            Mazda
54              BMW
55       Volkswagen
56          Mercury
57            Eagle
58           Hummer
59           Toyota
Name: make, dtype: object

In [303]:
# Braziliyalik xaridorlarni ajratib olamiz
query = "SELECT * FROM car WHERE make='Cadillac'"
df = pd.read_sql(query, pdb, index_col="id")
df.head(10)

C:\Users\user\AppData\Local\Temp\ipykernel_14312\3214104620.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, pdb, index_col="id")

         make         model    year     price
id
75   Cadillac      Escalade  2007.0  40982.32
180  Cadillac           DTS  2008.0  23656.54
190  Cadillac       DeVille  1997.0  11870.43
236  Cadillac         STS-V  2006.0  19488.30
380  Cadillac  Escalade ESV  2010.0  90152.37
410  Cadillac        Catera  2001.0  56361.65
452  Cadillac         CTS-V  2012.0  15003.98
464  Cadillac           CTS  2004.0  79063.59
476  Cadillac      Eldorado  1997.0  79670.42
490  Cadillac  Escalade EXT  2003.0   7590.59

In [339]:
# Brazil va USA xaridorlarni ajratib olamiz
# Keling boshlanishiga bunday xaridorlar sonini chiqaramiz
cursor1.execute("SELECT COUNT (*) FROM car WHERE make='Cadillac' OR make='Lexus'")
print(cursor1.fetchone())

(51,)

In [341]:
# Brazil va USA xaridorlarni ajratib olamiz
query = "SELECT make, model, price FROM car WHERE make='Cadillac' OR make='Lexus'"
pd.read_sql(query, pdb)

C:\Users\user\AppData\Local\Temp\ipykernel_14312\3663169156.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, pdb)

        make         model     price
0      Lexus            RX   6537.82
1      Lexus            LS  23342.25
2      Lexus            SC   7624.16
3      Lexus            IS  38720.66
4      Lexus            ES  81840.64
5   Cadillac      Escalade  40982.32
6      Lexus            GX  66979.20
7   Cadillac           DTS  23656.54
8      Lexus            ES  16166.85
9   Cadillac       DeVille  11870.43
10     Lexus            ES  37100.96
11  Cadillac         STS-V  19488.30
12     Lexus            LX  86301.13
13     Lexus            ES  29788.76
14     Lexus            ES  21677.30
15  Cadillac  Escalade ESV  90152.37
16     Lexus            CT  57917.39
17  Cadillac        Catera  56361.65
18  Cadillac         CTS-V  15003.98
19  Cadillac           CTS  79063.59
20     Lexus            IS  85475.91
21  Cadillac      Eldorado  79670.42
22     Lexus            ES  57507.16
23  Cadillac  Escalade EXT   7590.59
24     Lexus            LS  87876.47
25     Lexus            GS  47885.70
26     Lexus            LS   6861.89
27     Lexus            RX  14344.83
28     Lexus     LS Hybrid  80901.28
29  Cadillac         CTS-V  37629.67
30     Lexus            HS  64866.39
31     Lexus            LS   9531.97
32     Lexus            LX   4152.77
33     Lexus            GS  95127.04
34     Lexus            LS  98185.73
35  Cadillac  Escalade EXT  82692.25
36  Cadillac      Escalade   6091.01
37     Lexus            RX  95434.31
38     Lexus            LS  30226.08
39     Lexus            LX  80929.97
40     Lexus            LX  58752.42
41  Cadillac           SRX  86886.68
42     Lexus            LS  71220.81
43     Lexus            GS  15809.52
44     Lexus            IS  97142.16
45     Lexus            HS  16885.74
46     Lexus            ES  42992.75
47     Lexus            GS  30152.21
48     Lexus            IS  50548.04
49  Cadillac           CTS  78515.59
50  Cadillac  Escalade ESV  22627.71

In [343]:
pdb.close()